#!/opt/srv/php/bin/php
<?php
namespace SuperListd;

// search base installation dir
$basedir=preg_replace("/\/sbin(\/\.)*$/","",dirname($argv[0]));
if (!chdir($basedir))
{
  fprintf(STDERR,"Base Directory find %s ar not directory or accesible !\n",$basedir);
  exit(1);
}
$basedir=getcwd();
//fprintf(STDERR,"Basedir found:%s\n",$basedir);

// set include path based on basedir
set_include_path(get_include_path() . PATH_SEPARATOR . $basedir."/includes");

require_once("Debug.php");
require_once("SMTPDaemon.php");

$smtpd = new SMTPDaemon($basedir);
$smtpd->main($argc,$argv);
