#!/opt/srv/php/bin/php
<?php 
namespace SuperListd;

// setup base dire
require_once(__DIR__."/../includes/Setup.php");

// set the default startup debug log level 
Debug::$loglevel=LOG_WARNING;

// load SMTPDaemon
$smtpd = new SMTPDaemon($basedir);
$smtpd->main($argc,$argv);
